### ISSUE TITLE
Integrate old unfolding with robot platform for robotic unfolding

### ISSUE THREAD

**Issue by David-Estevez** [roboticslab-uc3m/textiles#17]
* [x] Robot remote Cartesian movement
* [x] Integration with old code (through new adapter)
* [x] Robot remote digital output activation
* [x] Data extraction (more or less automatic)
* [x] Robot moving to desired points

**Comment by jgvictores** [comment]
Updated "Robot remote digital output activation" as done.
@David-Estevez How is the status of the remaining points?
