### ISSUE TITLE
Improve README.md

### ISSUE THREAD

**Issue by jgvictores** [roboticslab-uc3m/textiles#21]
Improve README.md in description, links, contributions...

**Comment by jgvictores** [comment]
Mostly done at fd6242268d67680a0c41523afb9c2f18a0ee6c66
Still missing little story similar to https://github.com/roboticslab-uc3m/xgnitive

**Comment by jgvictores** [comment]
Done at 9573c8bade50eb643d843fca88b3708a54a4996b.

**Comment by David-Estevez** [comment]
Let me develop it a bit more.

**Comment by David-Estevez** [comment]
Improved at 3da0173 , closing issue again.
