### ISSUE TITLE
Import modules from textiles package does not work without Pycharm

### ISSUE THREAD

**Issue by David-Estevez** [roboticslab-uc3m/textiles#25]
When importing modules from the textiles package (e.g. common, ironing, etc) outside PyCharm an import error is raised.

This might be due to Pycharm including textiles submodules in the Python path, but needs to be fixed so that it can be run also outside PyCharm.

**Comment by jgvictores** [comment]
Not sure if relevant, but looks like @PeterBowman did a really good job at the [asibot-main](https://github.com/roboticslab-uc3m/asibot-main) repository (see [this](https://github.com/roboticslab-uc3m/asibot-main/blob/486aedf9a76f976b4924b7fcc6367f4f1f02be9b/CMakeLists.txt) and [this](https://github.com/roboticslab-uc3m/asibot-main/blob/6df5d98ff0b7cf6a6ff52772e0db80ea7a596db9/cmake/template/setup.py.in))

**Comment by David-Estevez** [comment]
Fixed in  9884f18

Relative imports are discouraged for clearness, and a proper textiles Python package didn't exist. The most obvious solution was then to add a textiles package to the repo instead of using the whole repo as a package (this wasn't even recognized by PyCharm). The only thing left, as @jgvictores stated, is to integrate CMake and setuptools to have textiles installed in the system (see issue #38).

Note that the changes done to solve this issue _**_will probably break any hardcoded paths present in the code_**_, but those shouldn't exist to start with, so it's ok.
