### ISSUE TITLE
KinectFusion version without GUI

### ISSUE THREAD

**Issue by David-Estevez** [roboticslab-uc3m/textiles#29]
Currently KinectFusion (PCL implementation) requires using a graphical session to display its OpenGL-based GUI. This includes not only the data adquisition step, but also the texture baking step. It also requires input from the user to finish (pressing the 'S' key to save the data), so it cannot be launched and controlled from other program automatically (unless keystrokes are emulated).

There are some applications that would benefit from a headless KinectFusion that could be integrated in the software pipeline and automated, as well as run in a headless server.

**Comment by David-Estevez** [comment]
This could be adapted to render KinectFusion offscreen, removing the need for any KinectFusion mods: https://www.openrobots.org/morse/doc/stable/headless.html

**Comment by jgvictores** [comment]
Thanks for the pointer! May be good for addressing https://github.com/roboticslab-uc3m/openrave-yarp-plugins/issues/48 without GPU.

[Here](https://github.com/jgvictores/snippets/tree/315d2fe740447d21e586dc769efe394c37e45af7/coin3d)'s a very small program that lets you test if you have offscreen rendering (aka indirect rendering, aka IGLX). Seems to be something in [mesa3d](https://www.mesa3d.org/envvars.html), e.g. `LIBGL_ALWAYS_INDIRECT`.

**Comment by PeterBowman** [comment]
We've got a YARP-backed KinFu architecture at https://github.com/roboticslab-uc3m/vision/issues/101. It runs OpenCV's rgbd module and its headless KinFu implementation under the hood.

**Comment by jgvictores** [comment]
@PeterBowman Okay to close issue?

**Comment by PeterBowman** [comment]
@jgvictores you should ask @David-Estevez as I'm not familiar at all with the Textiles project.

**Comment by jgvictores** [comment]
The main idea of this issue was having a Kinect Fusion or equivalent implementation which could be integrated within our pipeline:

- Commanded via an API
- Ideally, headless

Precisely, this was not possible with PCL's KinFu but should be fine via https://github.com/roboticslab-uc3m/vision/issues/101 ("Kinect Fusion as a service"). Closing issue!
