### ISSUE TITLE
pypcd does not work with Python 3

### ISSUE THREAD

**Issue by David-Estevez** [roboticslab-uc3m/textiles#40]
Functionality already requested in https://github.com/dimatura/pypcd/issues/7

**Comment by David-Estevez** [comment]
[This fork](https://github.com/klintan/pypcd) has recently added code to solve this, and it's waiting for the original author to merge the PR to the original repo.

**Comment by jgvictores** [comment]
> "You want to mess around with your point cloud data without writing C++ and waiting hours for the template-heavy PCL code to compile.
You tried to get some of the Python bindings for PCL to compile and just gave up."

❤️

**Comment by David-Estevez** [comment]
I really love their honesty
> ### Is it beautiful, production-ready code?
>
> No.
