### ISSUE TITLE
Write abstract for IROS 2018

### ISSUE THREAD

**Issue by David-Estevez** [roboticslab-uc3m/textiles#60]
Write abstract for IROS 2018

**Comment by David-Estevez** [comment]
@jgvictores I have uploaded to SVN (pendant/2018-iros-textiles) a brief proposal for this abstract, could you review it before sending it?

**Comment by jgvictores** [comment]
Perfect. Minor touch (added 1 word) at `r10789`.

**Comment by David-Estevez** [comment]
Shall I send it to Carlos?

**Comment by jgvictores** [comment]
Yes, please!

**Comment by David-Estevez** [comment]
Sent!

**Comment by jgvictores** [comment]
Perfect, thanks!
