### ISSUE TITLE
"textilesMover1" not a very descriptive name

### ISSUE THREAD

**Issue by David-Estevez** [roboticslab-uc3m/textiles#7]
I would suggest something like "TEOinterface" or "RobotInterface"

Or "RoboFolderInterface"

**Comment by jgvictores** [comment]
For now simply 'mover' https://github.com/roboticslab-uc3m/textiles/commit/7cdf38a52d76d8acf98b906254a78f9919d8e801. Further disambiguation will come when working wth other robot platforms.
